// Code generated by MockGen. DO NOT EDIT.
// Source: business/domain/parking/parking.go
//
// Generated by this command:
//
//	mockgen -source=business/domain/parking/parking.go -destination=mocks/domain/parking/mock_parking.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/zuhrulumam/doit-test/business/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDomainItf is a mock of DomainItf interface.
type MockDomainItf struct {
	ctrl     *gomock.Controller
	recorder *MockDomainItfMockRecorder
	isgomock struct{}
}

// MockDomainItfMockRecorder is the mock recorder for MockDomainItf.
type MockDomainItfMockRecorder struct {
	mock *MockDomainItf
}

// NewMockDomainItf creates a new mock instance.
func NewMockDomainItf(ctrl *gomock.Controller) *MockDomainItf {
	mock := &MockDomainItf{ctrl: ctrl}
	mock.recorder = &MockDomainItfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainItf) EXPECT() *MockDomainItfMockRecorder {
	return m.recorder
}

// GetAvailableParkingSpot mocks base method.
func (m *MockDomainItf) GetAvailableParkingSpot(ctx context.Context, data entity.GetAvailableParkingSpot) ([]entity.ParkingSpot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableParkingSpot", ctx, data)
	ret0, _ := ret[0].([]entity.ParkingSpot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableParkingSpot indicates an expected call of GetAvailableParkingSpot.
func (mr *MockDomainItfMockRecorder) GetAvailableParkingSpot(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableParkingSpot", reflect.TypeOf((*MockDomainItf)(nil).GetAvailableParkingSpot), ctx, data)
}

// GetVehicle mocks base method.
func (m *MockDomainItf) GetVehicle(ctx context.Context, data entity.SearchVehicle) (entity.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicle", ctx, data)
	ret0, _ := ret[0].(entity.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicle indicates an expected call of GetVehicle.
func (mr *MockDomainItfMockRecorder) GetVehicle(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicle", reflect.TypeOf((*MockDomainItf)(nil).GetVehicle), ctx, data)
}

// InsertVehicle mocks base method.
func (m *MockDomainItf) InsertVehicle(ctx context.Context, data entity.InsertVehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVehicle", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVehicle indicates an expected call of InsertVehicle.
func (mr *MockDomainItfMockRecorder) InsertVehicle(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVehicle", reflect.TypeOf((*MockDomainItf)(nil).InsertVehicle), ctx, data)
}

// UpdateParkingSpot mocks base method.
func (m *MockDomainItf) UpdateParkingSpot(ctx context.Context, data entity.UpdateParkingSpot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParkingSpot", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParkingSpot indicates an expected call of UpdateParkingSpot.
func (mr *MockDomainItfMockRecorder) UpdateParkingSpot(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParkingSpot", reflect.TypeOf((*MockDomainItf)(nil).UpdateParkingSpot), ctx, data)
}

// UpdateVehicle mocks base method.
func (m *MockDomainItf) UpdateVehicle(ctx context.Context, data entity.UpdateVehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVehicle", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVehicle indicates an expected call of UpdateVehicle.
func (mr *MockDomainItfMockRecorder) UpdateVehicle(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVehicle", reflect.TypeOf((*MockDomainItf)(nil).UpdateVehicle), ctx, data)
}
